export const ADD_POST = 'ADD_POST';
export const ADD_POST_ERROR = 'ADD_POST_ERROR';
export const ADD_POST_LOADING = 'ADD_POST_LOADING';

export const DELETE_POST = 'DELETE_POST';
export const DELETE_POST_ERROR = 'DELETE_POST_ERROR';
export const DELETE_POST_LOADING = 'DELETE_POST_LOADING';

export const EDIT_POST = 'EDIT_POST';
export const EDIT_POST_ERROR = 'EDIT_POST_ERROR';
export const EDIT_POST_LOADING = 'EDIT_POST_LOADING';

export const FETCH_POSTS = 'FETCH_POSTS';
export const FETCH_POSTS_ERROR = 'FETCH_POSTS_ERROR';
export const FETCH_POSTS_LOADING = 'FETCH_POSTS_LOADING';
